version: '3'

services:
  nginx:
    image: my-nginx:alpha
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    image: docker-experimentation:alpha
    ports:
      - "8090:8090"