version: '3'

services:
  nginx:
    image: nginx:alpha-0.1.0
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - main

  app:
    image: docker-experimentation:alpha
    ports:
      - "8090:8090"
    networks:
      - main

  keycloakdb:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: postgres
    networks:
      - main

  keycloak_web:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: postgres

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: change_me
    command: start-dev
    depends_on:
      - keycloakdb
    ports:
      - 8080:8080
    networks:
      - main


volumes:
  postgres_data:

networks:
  main:
    name: main
    driver: bridge